language: node_js
node_js: lts/*
os: linux
dist: bionic

before_install:
  - openssl aes-256-cbc -K $encrypted_47d48945fed9_key -iv $encrypted_47d48945fed9_iv -in server/deploy/keypair.config.js.enc -out server/deploy/keypair.config.js -d
## Uncomment the following lines if you require extra dependencies
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
# If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - source ./texlive/texlive_install.sh
  - yarn install --cwd server

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - source build-sub.sh SDE
  - cd server && yarn build
## Uncomment the following lines to see the packages installed in travis
# after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'
