sudo: required
language: generic
services: docker

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  # Compiling only main.tex:
  - docker run
    --mount src=$TRAVIS_BUILD_DIR/SDE/hw7,target=/usr/src/tex,type=bind
    --mount src=$TRAVIS_BUILD_DIR/latex-template,target=/template,type=bind
    dxjoke/tectonic-docker
    /bin/sh -c "TEXINPUTS='/template:' tectonic main.tex"
  # Compiling multiple files as well as using biber:
  #  - docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic --keep-intermediates --reruns 0 biber-mwe.tex; biber biber-mwe; tectonic biber-mwe.tex; tectonic main.tex"
