language: node_js
node_js: lts/*
os: linux
dist: bionic

before_install:
  - openssl aes-256-cbc -K $encrypted_47d48945fed9_key -iv $encrypted_47d48945fed9_iv
    -in server/deploy/keypair.config.js.enc -out server/deploy/keypair.config.js -d

install:
  - source ./texlive/texlive_install.sh
  - yarn install --cwd server

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
    - outputs
  yarn: true

script:
  - source start.sh
  - cd server && yarn build
  - yarn deploy
## Uncomment the following lines to see the packages installed in travis
# after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'
